version: '3.8'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
    - "./www:/usr/share/nginx/html:ro"
    - "./log:/var/log/nginx"
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
    - published: 80
      target: 80

  php:
    image: php:7.4-fpm-alpine
    container_name: php
    volumes:
    - "./www:/script:ro"